### ISSUE TITLE
Easy Rank Toggle

### ISSUE THREAD

**Issue by ReflexxMC** [RubyFreedom/RubyFreedomMod#1]
Similar to owner in config.yml but add ranks like co-owner, executives and co-owners, easy to config. If you need me to help, just tell me and i'll do it.

**Comment by falceso** [comment]
Would you like to be added to the RubyFreedom github page?

**Comment by ReflexxMC** [comment]
kk

**Comment by ReflexxMC** [comment]
Everything is working :+1:
