### ISSUE TITLE
Failing to Complie

### ISSUE THREAD

**Issue by ValenciaOrange** [RubyFreedom/RubyFreedomMod#5]
ant -f C:\\Users\\Sony\\Documents\\GitHub\\RubyFreedomMod -Dnb.internal.action.name=build jar
init:
Deleting: C:\Users\Sony\Documents\GitHub\RubyFreedomMod\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\Sony\Documents\GitHub\RubyFreedomMod\build\built-jar.properties
Compiling 193 source files to C:\Users\Sony\Documents\GitHub\RubyFreedomMod\build\classes
javac: invalid target release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options
C:\Users\Sony\Documents\GitHub\RubyFreedomMod\nbproject\build-impl.xml:900: The following error occurred while executing this line:
C:\Users\Sony\Documents\GitHub\RubyFreedomMod\nbproject\build-impl.xml:265: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 2 seconds)

http://i.imgur.com/RYDRjll.png

**Comment by tylerhyperHD** [comment]
You need to download the latest JDK of Java which is Java 8 to fix that.

On Tue, Aug 25, 2015 at 3:13 PM Valencia_Orange <notifications@github.com>
wrote:

> ant -f C:\Users\Sony\Documents\GitHub\RubyFreedomMod -
> Dnb.internal.action.name=build jar
> init:
> Deleting:
> C:\Users\Sony\Documents\GitHub\RubyFreedomMod\build\built-jar.properties
> deps-jar:
> Updating property file:
> C:\Users\Sony\Documents\GitHub\RubyFreedomMod\build\built-jar.properties
> Compiling 193 source files to
> C:\Users\Sony\Documents\GitHub\RubyFreedomMod\build\classes
> javac: invalid target release: 1.8
> Usage: javac
> use -help for a list of possible options
> C:\Users\Sony\Documents\GitHub\RubyFreedomMod\nbproject\build-impl.xml:900:
> The following error occurred while executing this line:
> C:\Users\Sony\Documents\GitHub\RubyFreedomMod\nbproject\build-impl.xml:265:
> Compile failed; see the compiler error output for details.
> BUILD FAILED (total time: 2 seconds)
>
> http://i.imgur.com/RYDRjll.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RubyFreedom/RubyFreedomMod/issues/5>.
>
-- 

Thanks!
Tyler Wrenn
Rising Senior at Deep Run High School

**Comment by ValenciaOrange** [comment]
Solved, Thanks
